# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gnm < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bentohset/gnm/releases/download/v0.0.1/gnm_Darwin_arm64.tar.gz"
      sha256 "8a950405ac51cfbda03ad9053daaf5cbb51edefaa9a987f9612e8d1b384f3fe7"

      def install
        bin.install "gnm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bentohset/gnm/releases/download/v0.0.1/gnm_Darwin_x86_64.tar.gz"
      sha256 "4a0430b636183b49696e2884ac0b9a593c55f413a90462cd6f9f17e2b13fa13a"

      def install
        bin.install "gnm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bentohset/gnm/releases/download/v0.0.1/gnm_Linux_arm64.tar.gz"
      sha256 "804a261ecf804d13f75af95b27e358e5e6c35f013589463357a8271667fbe15a"

      def install
        bin.install "gnm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bentohset/gnm/releases/download/v0.0.1/gnm_Linux_x86_64.tar.gz"
      sha256 "68b4a8d43ed46461e567f33c4d92304f8b3269bff2c7eb7fcb8a5cdecb9458eb"

      def install
        bin.install "gnm"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/bentohset/gnm/releases/download/v0.0.1/gnm_Linux_armv6.tar.gz"
      sha256 "bbb0c6b8ccf1dd375cfd8aeb9076f1d7d6518ea3ef7d927e32aaffd88d1737c7"

      def install
        bin.install "gnm"
      end
    end
  end
end
